### ISSUE TITLE
graphql 服务启动失败

### ISSUE THREAD

**Issue by mt-ik** [liangwei0101/egg-demo#5]
您好，看到您这个关于graphql在ts下的用法，想学习下，按照您的代码运行，egg服务正常启动，但是graphql服务失败，辛苦您，有时间时帮看下，谢谢！
失败信息：
 [ '/Users/xugy/xugy/egg-space/mt.ik.sunyata/app/graphql/schemaResolver/studentResolver.ts']
(node:89254) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
(node:89254) DeprecationWarning: This Package got moved, please use `@hasezoey/typegoose` | github:hasezoey/typegoose
2019-12-28 18:15:43,376 INFO 89254 graphql server init
(node:89254) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
node_redis: Warning: Redis server does not require a password, but a password was supplied.
node_redis: Warning: Redis server does not require a password, but a password was supplied.
2019-12-28 18:15:43,470 INFO 89243 [master] egg started on http://127.0.0.1:7001 (2912ms) with STICKY MODE!
2019-12-28 18:18:08,043 ERROR 89254 [-/127.0.0.1/-/10ms POST /graphql?] nodejs.GraphQLError: Syntax Error: Unexpected <EOF>
    at syntaxError (/Users/xugy/xugy/egg-space/mt.ik.sunyata/node_modules/graphql/error/syntaxError.js:15:10)
    at Parser.unexpected (/Users/xugy/xugy/egg-space/mt.ik.sunyata/node_modules/graphql/language/parser.js:1463:41)
    at Parser.parseDefinition (/Users/xugy/xugy/egg-space/mt.ik.sunyata/node_modules/graphql/language/parser.js:157:16)
    at Parser.many (/Users/xugy/xugy/egg-space/mt.ik.sunyata/node_modules/graphql/language/parser.js:1518:26)
    at Parser.parseDocument (/Users/xugy/xugy/egg-space/mt.ik.sunyata/node_modules/graphql/language/parser.js:111:25)
    at Object.parse (/Users/xugy/xugy/egg-space/mt.ik.sunyata/node_modules/graphql/language/parser.js:36:17)
    at Object.buildSchemaFromTypeDefinitions (/Users/xugy/xugy/egg-space/mt.ik.sunyata/node_modules/graphql-tools/src/generate/buildSchemaFromTypeDefinitions.ts:37:19)
    at makeExecutableSchema (/Users/xugy/xugy/egg-space/mt.ik.sunyata/node_modules/graphql-tools/src/makeExecutableSchema.ts:52:18)
    at Application.get (/Users/xugy/xugy/egg-space/mt.ik.sunyata/node_modules/egg-graphql/lib/load_schema.js:72:31)
    at /Users/xugy/xugy/egg-space/mt.ik.sunyata/node_modules/egg-graphql/app/middleware/graphql.js:68:23
    at dispatch (/Users/xugy/xugy/egg-space/mt.ik.sunyata/node_modules/koa/node_modules/koa-compose/index.js:42:32)
    at passportSession (/Users/xugy/xugy/egg-space/mt.ik.sunyata/node_modules/egg-passport/lib/framework.js:59:12)
    at dispatch (/Users/xugy/xugy/egg-space/mt.ik.sunyata/node_modules/koa/node_modules/koa-compose/index.js:42:32)
    at passportInitialize (/Users/xugy/xugy/egg-space/mt.ik.sunyata/node_modules/egg-passport/lib/framework.js:36:12)
    at dispatch (/Users/xugy/xugy/egg-space/mt.ik.sunyata/node_modules/koa/node_modules/koa-compose/index.js:42:32)
    at /Users/xugy/xugy/egg-space/mt.ik.sunyata/node_modules/egg-development/app/middleware/egg_loader_trace.js:9:56
message: "Syntax Error: Unexpected <EOF>"
locations: [{"line":1,"column":1}]
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 89254
hostname: xuMacBook-Pro.local

**Comment by mt-ik** [comment]
已解决
